### ISSUE TITLE
os-projects.yml requires Ansible 2.5 and under.

### ISSUE THREAD

**Issue by brtkwr** [SKA-ScienceDataProcessor/p3-config#50]
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/47
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/49

Hitting this error:
```
Traceback (most recent call last):
  File "/home/stack/.ansible/tmp/ansible-tmp-1543576973.47-244269623783008/AnsiballZ_os_project.py", line 113, in <module>
    _ansiballz_main()
  File "/home/stack/.ansible/tmp/ansible-tmp-1543576973.47-244269623783008/AnsiballZ_os_project.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/stack/.ansible/tmp/ansible-tmp-1543576973.47-244269623783008/AnsiballZ_os_project.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_os_project_payload_W2JPpe/__main__.py", line 211, in <module>
  File "/tmp/ansible_os_project_payload_W2JPpe/__main__.py", line 156, in main
  File "/tmp/ansible_os_project_payload_W2JPpe/ansible_os_project_payload.zip/ansible/module_utils/openstack.py", line 121, in openstack_cloud_from_module
AttributeError: 'module' object has no attribute 'version'
```

**Comment by brtkwr** [comment]
We are also seeing this:
```
Traceback (most recent call last):
 File "/tmp/ansible_VROLXu/ansible_module_os_quota.py", line 515, in <module>
 main()
 File "/tmp/ansible_VROLXu/ansible_module_os_quota.py", line 450, in main
 shade, module, cloud, cloud_params['name'])
 File "/tmp/ansible_VROLXu/ansible_module_os_quota.py", line 317, in _get_quotas
 quota['volume'] = _get_volume_quotas(cloud, project)
 File "/tmp/ansible_VROLXu/ansible_module_os_quota.py", line 300, in _get_volume_quotas
 return cloud.get_volume_quotas(project)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/operatorcloud.py", line 2209, in get_volume_quotas
 error_message="cinder client call failed")
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 234, in get
 return self.request(url, 'GET', **kwargs)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/_adapter.py", line 197, in request
 response = self.manager.submit_task(RequestTask(**kwargs))
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/task_manager.py", line 260, in submit_task
 return self.run_task(task=task, raw=raw)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/task_manager.py", line 271, in run_task
 return self._run_task(task, raw=raw)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/task_manager.py", line 285, in _run_task
 return task.wait(raw)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/task_manager.py", line 99, in wait
 self._traceback)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/task_manager.py", line 110, in run
 self.done(self.main(client))
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/shade/_adapter.py", line 195, in main
 return request_method(**self.args)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 159, in request
 return self.session.request(url, method, **kwargs)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
 return wrapped(*args, **kwargs)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/session.py", line 513, in request
 **endpoint_filter)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/session.py", line 856, in get_endpoint
 return auth.get_endpoint(self, **kwargs)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 219, in get_endpoint
 service_name=service_name)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
 return wrapped(*args, **kwargs)
 File "/home/stack/p3-config-venv/lib/python2.7/site-packages/keystoneauth1/access/service_catalog.py", line 228, in url_for
 raise exceptions.EndpointNotFound(msg)
keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for volumev2 service not found
```

Related: https://github.com/ansible/ansible/issues/41240

Temporary fix:
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/51
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/52

**Comment by brtknr** [comment]
https://github.com/SKA-ScienceDataProcessor/p3-config/issues/50

**Comment by brtknr** [comment]
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/51
https://github.com/SKA-ScienceDataProcessor/p3-config/pull/52
